/**
 * Created by gaurav.m on 3/31/17.
 */
export const FETCH_WIDGETS="FETCH_WIDGETS"
export const FETCH_DEFAULT_SETTINGS="FETCH_DEFAULT_SETTINGS"
export const FETCH_USER_LIST="FETCH_USER_LIST"
export const RECIEVE_USER_LIST="RECIEVE_USER_LIST"
export const WS_CONNECT="WS_CONNECT"
export const WS_AUTHENTICATED="WS_AUTHENTICATED"
export const WS_DISCONNECT="WS_DISCONNECT"
export const WS_CONNECTED="WS_CONNECTED"
export const WS_ONMESSAGE="WS_ONMESSAGE"
export const WS_ONSEND="WS_ONSEND"
export const WS_END="WS_END"
export const REQUEST_HEADER="REQUEST_HEADER"
export const RECIEVE_HEADER="RECIEVE_HEADER"
export const RECIEVE_ITEM_TO_STOCK="RECIEVE_ITEM_TO_STOCK"
export const DATA_SUBSCRIPTION_PACKET="DATA_SUBSCRIPTION_PACKET"
export const WS_SUBSCRIBED="WS_SUBSCRIBED"
